name: Deploy to Firebase Hosting (web)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build & Deploy to Firebase Hosting (web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js 20
        uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite web application
        run: npm run build

      - name: Deploy to Firebase Hosting (web)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: 'device-streaming-ccab91bb'
          channelId: live
          target: web